site_name: Methylator Documentation

nav:
  - Home: index.md
  - Biological context :  biological_context.md
  - Before starting: before_start.md
  - Installation: installation.md
  - Description: description.md
  - Adapt the workflow to cluster: adapt_cluster.md
  - Transfert your data: transfert_data.md
  - Preparing the run : preparing_run.md
  - Configuration files examples : configuration_file_example.md
  - Annotations : annotations.md
  - Quick start with the test dataset : quick_start.md
  - Running your analysis step by step: running.md
  - Results: results.md
  - Extra help !: extra_help.md
  - Singularity: singularity_image.md
  - Resources: resources.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/parisepigenetics/WGBSflow

copyright: Copyright &copy; 2024 Methylator, Epigenetics and Cell Fate 

theme:
  logo: img/methylator_logo.png
  features:
    - content.code.copy
    - content.code.select
  hljs_languages:
    - yaml
    
  name: readthedocs
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  plugins:
  - search
  - git-revision-date-localized
      
