site_name: Methylator Documentation
nav:
  - Home: index.md
  - Before starting: before_start.md
  - Running your analysis step by step: running.md
  - Extra help !: extra_help.md
  - Resources: resources.md
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: readthedocs
  icon:
    admonition:
      <type>: <icon> 
