site_name: Methylator Documentation
nav:
  - Home: index.md
  - Resources: resources.md
  - Before starting: before_start.md
  - Extra help !: extra_help.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: readthedocs
  icon:
    admonition:
      <type>: <icon> 
