site_name: Methylator Documentation
nav:
  - Home: index.md
  - Before starting: before_start.md
  - Installation and description: installation.md
  - Adapt the workflow to cluster: adpat_cluster.md
  - Transfert your data: transfert_data.md
  - Running your analysis step by step: running.md
  - Extra help !: extra_help.md
  - Resources: resources.md
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  features:
    - content.code.copy
    - content.code.select
  name: readthedocs
  icon:
    admonition:
      <type>: <icon> 
