site_name: Methylator Documentation

nav:
  - Home: index.md
  - Before starting: before_start.md
  - Installation: installation.md
  - Description: description.md
  - Adapt the workflow to cluster: adapt_cluster.md
  - Transfert your data: transfert_data.md
  - Configuration files examples : configuration_file_example.md
  - Running your analysis step by step: running.md
  - Results: results.md
  - Extra help !: extra_help.md
  - Singularity: singularity_image.md
  - Resources: resources.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
theme:
  features:
    - content.code.copy
    - content.code.select
    
  name: readthedocs
  
  icon:
    admonition:
      <type>: <icon> 
